SPDX-FileCopyrightText = "2026 Elio Severo Junior and contributors"
SPDX-PackageDownloadLocation = "https://github.com/elioseverojunior/xllm"
SPDX-PackageName = "xllm"
SPDX-PackageSupplier = "XLLM contributors"
version = 1

[[annotations]]
SPDX-FileCopyrightText = "2026 Elio Severo Junior and contributors"
SPDX-License-Identifier = "MIT OR Apache-2.0"
path = ["**"]
precedence = "aggregate"

[[annotations]]
SPDX-License-Identifier = "MIT"
path = ["LICENSES/MIT.txt"]
precedence = "aggregate"

[[annotations]]
SPDX-License-Identifier = "Apache-2.0"
path = ["LICENSES/Apache-2.0.txt"]
precedence = "aggregate"

[[annotations]]
SPDX-FileCopyrightText = "2026 Creative Commons"
SPDX-License-Identifier = "CC-BY-3.0"
path = ["LICENSES/CC-BY-3.0.txt"]
precedence = "aggregate"

[[annotations]]
SPDX-License-Identifier = "MIT"
path = ["DCO.txt"]
precedence = "aggregate"
