
# cargo-vet audits file

[audits]

[[trusted.RazrFalcon]]
criteria = "safe-to-deploy"
user-id = 725782
start = "2018-06-01"
end = "2027-07-12"

[[trusted.cuviper]]
criteria = "safe-to-deploy"
user-id = 7222
start = "2015-06-01"
end = "2027-07-12"

[[trusted.dtolnay]]
criteria = "safe-to-deploy"
user-id = 3618
start = "2019-03-11"
end = "2027-07-12"

[[trusted.joshlf]]
criteria = "safe-to-deploy"
user-id = 57559
start = "2015-01-01"
end = "2027-07-12"

[[trusted.rust-lang-owner]]
criteria = "safe-to-deploy"
user-id = 12965
start = "2014-01-01"
end = "2027-07-12"

[[trusted.starkat99]]
criteria = "safe-to-deploy"
user-id = 107926
start = "2018-01-01"
end = "2027-07-12"

[[trusted.taiki-e]]
criteria = "safe-to-deploy"
user-id = 206278
start = "2017-01-01"
end = "2027-07-12"
