
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[imports.zcash]
url = "https://raw.githubusercontent.com/zcash/rust-ecosystem/main/supply-chain/audits.toml"

[[exemptions.crossbeam-deque]]
version = "0.8.7"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-epoch]]
version = "0.9.20"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-utils]]
version = "0.8.22"
criteria = "safe-to-deploy"

[[exemptions.half]]
version = "2.7.1"
criteria = "safe-to-deploy"

[[exemptions.libc]]
version = "0.2.186"
criteria = "safe-to-deploy"

[[exemptions.memmap2]]
version = "0.9.11"
criteria = "safe-to-deploy"

[[exemptions.quote]]
version = "1.0.46"
criteria = "safe-to-deploy"

[[exemptions.rayon]]
version = "1.12.0"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "2.0.118"
criteria = "safe-to-deploy"

[[exemptions.unicode-ident]]
version = "1.0.24"
criteria = "safe-to-deploy"

[[exemptions.zerocopy]]
version = "0.8.54"
criteria = "safe-to-deploy"

[[exemptions.zerocopy-derive]]
version = "0.8.54"
criteria = "safe-to-deploy"
