[advisories]
ignore = []
informational_warnings = []
severity_threshold = "medium"

[database]
fetch = true
stale = false

[output]
format = "terminal"
quiet = false
show_tree = true

[yanked]
enabled = true
update_index = true
